swagger: '2.0'
info:
  title: 投票系统接口文档
  description: 投票系统
  version: 1.0.0
host: '127.0.0.1:3000'
basePath: /v1
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /activity/everyDay:
    get:
      summary: 获取游戏每日活动列表
      description: 获取游戏每日活动列表
      tags:
        - activity
      parameters: []
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  '/activity/everyDay/award/{id}':
    post:
      summary: 每日活动奖品领取
      description: 每日活动奖品领取
      tags:
        - activity
      parameters:
        - name: id
          in: path
          description: 每日活动列表id
          required: true
          type: string
        - name: player
          in: formData
          description: 玩家名称
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
          code: 123
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /admin/list:
    get:
      summary: 管理员列表
      description: 管理员列表查询
      tags:
        - admin
      parameters: []
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  '/admin/list/{id}':
    put:
      summary: 管理员修改
      description: 管理员修改
      tags:
        - admin
      parameters:
        - name: id
          in: path
          description: 管理员id
          required: true
          type: string
        - name: authorized
          in: formData
          description: '权限 [管理，用户，游戏，数据，活动]  0 - 否  1 - 有 如[1,1,1,1,1]'
          required: false
          type: object
        - name: status
          in: formData
          description: 状态
          required: false
          type: string
        - name: password
          in: formData
          description: 密码
          required: false
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
    delete:
      summary: 管理员删除
      description: 管理员删除
      tags:
        - admin
      parameters:
        - name: id
          in: path
          description: 管理员id
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /auth/login:
    post:
      summary: 用户登录
      description: 用户输入有账户名称
      tags:
        - auth
      parameters:
        - name: username
          in: formData
          description: 账号
          required: true
          type: string
        - name: password
          in: formData
          description: 密码
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /data/list:
    get:
      summary: 获取游戏列表
      description: 获取游戏列表
      tags:
        - data
      parameters: []
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /data/create:
    post:
      summary: 添加游戏
      description: 添加游戏
      tags:
        - data
      parameters:
        - name: name
          in: formData
          description: 游戏名称
          required: true
          type: string
        - name: english_name
          in: formData
          description: 英文游戏名称
          required: true
          type: string
        - name: status
          in: formData
          description: 上线状态 状态：1-上线 2-即将上线
          required: true
          type: string
        - name: banner
          in: formData
          description: banner链接
          required: true
          type: string
        - name: url
          in: formData
          description: 游戏链接
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  '/data/list/{id}':
    put:
      summary: 修改游戏信息
      description: 修改游戏信息
      tags:
        - data
      parameters:
        - name: id
          in: path
          description: 候选人id
          required: true
          type: string
        - name: status
          in: formData
          description: 上线状态 状态：1-上线 2-即将上线
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /data/record:
    get:
      summary: 获取游戏记录
      description: 获取游戏列表
      tags:
        - data
      parameters:
        - name: dataId
          in: formData
          description: 游戏id
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /game/list:
    get:
      summary: 获取游戏列表
      description: 获取游戏列表
      tags:
        - game
      parameters:
        - name: startTime
          in: query
          description: 开始时间
          required: false
          type: string
        - name: endtTime
          in: query
          description: 开始时间
          required: false
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  '/game/record/{id}':
    get:
      summary: 获取游戏记录
      description: 获取游戏列表
      tags:
        - game
      parameters:
        - name: id
          in: path
          description: 游戏id
          required: true
          type: string
        - name: pageSize
          in: query
          description: 一次多少条
          required: true
          type: string
        - name: page
          in: query
          description: 多少页
          required: true
          type: string
        - name: startTime
          in: query
          description: 查询开始时间
          required: false
          type: string
        - name: endTime
          in: query
          description: 查询结束时间
          required: false
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /notice/list:
    get:
      summary: 获取公告列表
      description: 获取公告列表
      tags:
        - notice
      parameters: []
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /notice/create:
    post:
      summary: 添加公告
      description: 每日活动奖品领取
      tags:
        - notice
      parameters:
        - name: title
          in: formData
          description: 标题
          required: true
          type: string
        - name: content
          in: formData
          description: 内容
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /user/register:
    post:
      summary: 用户注册
      description: 用户输入有账户名称
      tags:
        - user
      parameters:
        - name: player
          in: formData
          description: 账号名称
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
  /user/list:
    get:
      summary: 用户列表
      description: 用户列表
      tags:
        - user
      parameters:
        - name: player
          in: query
          description: 账号名称
          required: false
          type: string
        - name: startTime
          in: query
          description: 查询开始时间
          required: false
          type: string
        - name: endTime
          in: query
          description: 查询结束时间
          required: false
          type: string
        - name: pageSize
          in: query
          description: 查询条数
          required: true
          type: string
        - name: page
          in: query
          description: 查询页数
          required: true
          type: string
      responses:
        '200':
          description: 通过返回值来标示执行结果　返回true表示执行成功
        default:
          description: '操作异常,执行失败.返回信息描述错误详情'
